### ISSUE TITLE
Add Support for Hubitat Package Manager

### ISSUE THREAD

**Issue by navarr** [esimioni/lutron-aurora-hubitat#1]
It would be awesome if you could add support for the Package Manager!

https://github.com/dcmeglio/hubitat-packagemanager/blob/master/README.md

- [x] Add Package & Repository JSON files
- [x] PR to HPM adding Repository to HPM

**Comment by esimioni** [comment]
Hello @navarr, would you be able to provide a pull request for this?
I'm quite busy at the moment.

**Comment by navarr** [comment]
Package is in HPM and can be installed.
